### ISSUE TITLE
Sana Ulaşamıyorum

### ISSUE THREAD

**Issue by puskuruk** [aniliyidogan/blog#2]
mail@aniliyidogan.com ==> mailini check edebilir misin? Bayadır ulaşamıyorum o yüzden buraya yazmak zorunda kaldım.

**Comment by aniliyidogan** [comment]
ahahah çok iyi :D kusura bakma aklımdaydı fakat unutmuşum, telegram kullanıcı adım: `aniliyidogan` buradan devam edebiliriz. @puskuruk

**Comment by puskuruk** [comment]
Tamamdır, kusuruma bakma :D
